### ISSUE TITLE
timestamp feature request.

### ISSUE THREAD

**Issue by ponas-niekas** [wtarreau/bootterm#3]
First of all thanks for bootterm, your "Motivation" section resonates with me.

I do have a feature request though - ability to optionally (with a single-character command/config file) prepend every line in the terminal/output with a (configurable?) timestamp, ala "[yyy.mm.dd hh:mm:ss] ..." . It's very useful to have timing information when debugging various issues.

P.S. 
minicom has this feature (Ctrl+A + N), but it has other issues, as you mentioned in "Motivation" section. 
"tio" has it, but it's not configurable, shows only time without date.

**Comment by wtarreau** [comment]
Hehe what I love is that for now the features that people request have been on my todo list for the same reasons. For me timestamps are important for kernel boot messages. I even reserved `-T` on the command line for this. I was thinking also about a relative timestamp mode (i.e. first line=0). I hesitated about letting the user adjust the timestamp format using `strftime()` or not. But I'd also want to have sub-second resolution by default (especially for boot delays).

I didn't know minicom had this, and I didn't know about "tio", thanks for the info! I just hope I'm not redeveloping something that already exists, I hate when others do this :-)

**Comment by cvubrugier** [comment]
It would be nice if BootTerm could be used to measure the boot time and investigate ways to improve it.

In the past, I used Minicom (_timestamp_ with Ctrl + A + N and _capture_ with Ctrl + A + L), but I had to parse the timestamps to compute the duration between two lines.
I also used [Grabserial](https://elinux.org/Grabserial) which is tailored for capturing and timestamping, but I got mixed results with it.

Overall, I think adding this feature is not like reinventing the wheel because the existing alternatives are not entirely satisfying.

**Comment by wtarreau** [comment]
Interesting point about using differential timing as well, that's definitely a good idea. So maybe we'll have just a few timestamp modes such as:
  - none (default)
  - absolute time (YYYY-mm-dd HH:MM:SS.us)
  - relative time to start of capture (SSSS.us)
  - relative time since previous line (SSSS.us)
I know the microsecond accuracy is ridiculous when speaking about serial ports, given that a 40-chars line at 115200 bps will take 3ms, but I think the 3 extra chars don't cost much and can be useful when they matter.

**Comment by wtarreau** [comment]
Please have a look at the latest master, I've implemented what I described above. You can enable timestamps using "-t" or using the `BT_TIMESTAMP_MODE` environment variable. The time relative to previous line is proposed using `-t line`. Please just let me know if we can close this issue now.

**Comment by ponas-niekas** [comment]
I tested latest code briefly and it works great. However, I expected to see timestamps in live terminal as well, not only in captures / log file. At least that's how timestamp feature works in Minicom and tio. 

So... any chance you could add an option to see timestamps in "live" terminal as well ? With something like "-T {none|term}", none being the default. And then, it would be great to be able to enable/disable timestamps in the live terminal with a "single-character command". That's my selfish request (which I'm pretty sure would be useful to many), but if you would implement it, I would deploy bootterm in production monitoring many hundreds serial ports :).

P.S. Never realized how useful "-t init" and "-t line" is, I think that's unique to bootterm.

**Comment by wtarreau** [comment]
Oh it could be done, but are you *really* sure it would be useful ? I mean, you will only be able to work in line mode. Just issuing "vi" on a text file will result in crap due to the positions on the screen and the terminal to be shifted. Even shell line editing will be confusing. However, I can understand that for pure line dumps (kernel boot messages etc) that could occasionally be useful, but I'm still having quite some doubts. What use case do you have in mind, to help me figure how to best do it ?

**Comment by ponas-niekas** [comment]
My use case is device testing by enabling/disabling various features via command line in serial terminal. Devices also periodically print messages to terminal as various events happen and that's where timing information is very very interesting. Some events happen quickly, others few times a day. With timestamps we are able to correlate/verify that stuff happen when it suppose to happen, not earlier or later.

You are absolutely right that timestamps in terminal mess up "vi" and other programs, that's why it would be great to be able to enable/disable timestamps in terminal with a "single-character command". In that case, one can disable timestamps, edit files(s), then enable timestamps again if needed. It would make bootterm very versatile.

**Comment by wtarreau** [comment]
Then why not just `tail -f bootterm-$date.log` in another window and see it updated continuously ? It's not that I don't want to make it, I'm just trying to figure the real value :-)

**Comment by ponas-niekas** [comment]
Well, simplified version is that a remote client opens en interactive session with a serial terminal, where it writes commands and monitors their output/event prints. It would take a separate process to tail capture file, right? So now we would have 2 processes, which must coordinate/be in sync with each other about what´s going on. That´s just unnecessary complexity, in my opinion.

**Comment by wtarreau** [comment]
You mean it would be a software, not a human, then ?

**Comment by ponas-niekas** [comment]
Yes, everything is automated.

**Comment by wtarreau** [comment]
OK got it now, and then I can indeed imagine it makes sense, and even to use the same format in captures and terminal since you won't use both at a time. Reliably writing to the terminal will be a bit more complicated since we have to deal with partial writes, hence modify the buffer itself in place. But we could us this as a standard way to use the buffers, i.e. double them and never allow the read side to fill more than half of a buffer so that we always have enough room to write timestamps, menus etc. I'll see what I can do.

**Comment by ponas-niekas** [comment]
ping :)

**Comment by wtarreau** [comment]
Sorry, having been quite busy on other projects lately. I can't promise anything before at best next week I'm afraid.

**Comment by wtarreau** [comment]
By the way, I'm still on it but it's more problematic than I initially estimated, because some boot loaders' SPL code emit \n\r which cause the timestamp to be printed at the wrong location or overwritten. I need to completely change the line processing code just to deal with this, and it will impact the capture code.

**Comment by ponas-niekas** [comment]
No worries, I know that last few corner cases usually take most of the time and effort :).

**Comment by wtarreau** [comment]
I figured a 4-state machine that should solve this and also deal with bare CR. I'll probably change the way captures work to mutualize the effort.

**Comment by wtarreau** [comment]
OK it works for me now, I've pushed the code. As indicated in the readme, there's a subtle difference between the way timestamps are emitted on the terminal and in the captures, because in captures we try hard to print the time of the first char on the line, but doing so in terminal mode would render the terminal unusable, given that it wouldn't report anything until a character is echoed. So in terminal mode you're seeing the time of the new line, so if the previous message was printed before starting the corresponding command, you will only see the processing time as part of the next line. Most of the time it's not an issue as lines report statuses (i.e. "scan found 3 ports" etc) and the processing time is indeed part of the line.

Please give it a try. I'm thinking about tagging it version 0.3. I've also added argument -T to enable them from the command line as I suspect it should ease your automation over sending <esc> T.

**Comment by wtarreau** [comment]
Released 0.3 now with this added. Please let me know your feedback so that we can close this issue (I'd rather not keep them opened too long).

**Comment by ponas-niekas** [comment]
I tested latest code briefly and found no issues, works as expected. Thanks! :)

**Comment by wtarreau** [comment]
OK, thanks for the quick feedback. Now closing then!
